<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<div class="wishlist-section">
    <div class="container">
        <?php if (count($block->getItems())) : ?>
            <div class="row">
                <?php foreach ($block->getItems() as $item) : ?>
                    <div class="col-lg-3 col-6 p-2 m-0">
                    <div data-row="product-item" class="wish-card wish_product-card" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
                        <div class="product-item-info" data-container="product-grid">
                            <?php foreach ($columns as $column) : ?>
                                <?= $column->setItem($item)->toHtml();?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        <?php else : ?>
            <div class="message info empty">
                <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php foreach ($columns as $column) : ?>
<?php endforeach; ?>
