<?php
/**
 * Product list toolbar (custom Bootstrap style)
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getAvailableOrders()) : ?>
    <div class="filter-div">
        <label for="sorter" class="me-2"><?= $block->escapeHtml(__('Sort By:')) ?></label>
        <select 
            id="sorter"
            class="form-select form-select-sm d-inline-block w-auto"
            data-role="sorter">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isOrderCurrent($_key)) : ?>
                        selected="selected"
                    <?php endif; ?>>
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <?php if ($block->getCurrentDirection() == 'desc') : ?>
            <button 
                class="btn btn-light btn-sm border ms-2"
                title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
                data-role="direction-switcher"
                data-value="asc">
                <i class="bi bi-sort-alpha-up"></i>
            </button>
        <?php else : ?>
            <button 
                class="btn btn-light btn-sm border ms-2"
                title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
                data-role="direction-switcher"
                data-value="desc">
                <i class="bi bi-sort-alpha-down"></i>
            </button>
        <?php endif; ?>
    </div>
<?php endif; ?>
