<?php
/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="footer">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                 <?= $block->getLayout()->getBlock('PageBuilderRenderer')->setIdentifier('section-423166')->toHtml(); ?> 
            </div>
        </div>
<script>
jQuery(document).ready(function($) {
    // Use event delegation for dynamically loaded elements
    $(document).on('click', '.gmt-element-21935ea .gmt-icon i.fas.fa-bars', function() {
        $('nav[data-action="navigation"]').slideToggle(400); // toggle menu
        $(this).toggleClass('active'); // rotate icon
    });
});
</script>

        </div>
    </div>
</div>
