<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/?>
<div class="order-details-items ordered">
    <?php $_order = $block->getOrder() ;  
        ?>
<div class="tracker-main d-flex justify-content-between align-items-start flex-wrap">
  <div>
    <h3 class="order_id_title">Order ID: <?= $_order->getIncrementId(); ?></h3>
    <div class="order_detail">
      <ul>
        <li>Order date: <span>Sep 16, 2025</span></li>
        <li class="estimate_delivery">
          <img src="<?=$block->getViewFileUrl('images/truck-tick.png'); ?>" alt="img"> Estimated delivery: Oct 16, 2025
        </li>
      </ul>
    </div>
  </div>

  <div class="order_buttons d-flex gap-2 mt-2 mt-md-0">
        <a href="/sales/guest/invoice/order_id/<?= $_order->getId(); ?>/"
           class="action print btn invoice_btn"
           rel="noopener">
            <img src="<?=$block->getViewFileUrl('images/invoice.png'); ?>" alt="Invoice" class="me-2"> Invoice
        </a>
    <?php foreach($_order->getShipmentsCollection() as $_shipment) : ?>
    <a href="#"
           data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($_shipment)) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
           title="<?= $block->escapeHtml(__('Track this shipment')) ?>"
           class="action track btn track_btn text-white" style="    background-color: #fa6905;">
          Track order <img src="<?=$block->getViewFileUrl('images/location.png'); ?>" alt="Track" class="ms-2">
        </a>
    <?php endforeach; ?>
    
  </div>
</div>
<div class="container p-0">
    <div class="progress-container p-0">
      <div class="progress-line"></div>
      <div class="progress-line-active" style="width: 50%;"></div>
      <div class="progress-steps">
        <div class="step <?php if($_order->getStatus() === "pending" || $_order->getStatus() === "processing" || $_order->getStatus() === "shipped" || $_order->getStatus() === "complete"){?>  active <?php } ?>">
          <div class="step-title">Order Confirmed</div>
          <div class="circle"></div>
          <div class="step-date">Wed, 11<sup>th</sup> Oct</div>
        </div>
        <div class="step <?php if($_order->getStatus() === "complete" || $_order->getStatus() === "shipped"){?>  active <?php } ?>">
          <div class="step-title">Shipped</div>
          <div class="circle"></div>
          <div class="step-date">Wed, 11<sup>th</sup> Oct</div>
        </div>
        <div class="step <?php if($_order->getStatus() === "complete"){?>  active <?php } ?>">
          <div class="step-title">Out For Delivery</div>
          <div class="circle"></div>
          <div class="step-date">Wed, 11<sup>th</sup> Oct</div>
        </div>
        <div class="step <?php if($_order->getStatus() === "complete"){?>  active <?php } ?>">
          <div class="step-title">Delivered</div>
          <div class="circle"></div>
          <div class="step-date expected-date">Expected by, Mon 16<sup>th</sup> Oct</div>
        </div>
      </div>
    </div>
  </div>
    <?= $block->getChildHtml('order_items') ?>

    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order', $_order)
        && $_order->getGiftMessageId()
    ) : ?>
    <div class="block block-order-details-gift-message">
        <div class="block-title"><strong><?= $block->escapeHtml(__('Gift Message for This Order')) ?></strong></div>
        <?php
        $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($_order);
        ?>
        <div class="block-content">
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?= $block->escapeHtml(__('From')) ?></strong><?= $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?= $block->escapeHtml(__('To')) ?></strong><?= $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message">
                    <?= /* @noEscape */
                    $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($_order) ?>
                </dd>
            </dl>
        </div>
    </div>
    <?php endif; ?>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>
