<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */
?>

<a href="#" data-role="remove" data-post-remove='<?= /* @noEscape */ $block->getItemRemoveParams($block->getItem()) ?>' title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete">
    <span style="display: flex; gap: 10px;"><img src="<?= $block->getViewFileUrl('images/delete.png'); ?>" alt="Remove">
<?= $block->escapeHtml(__('Remove item')) ?></span>
</a>
