<?php

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$urlBuilder = \Magento\Framework\App\ObjectManager::getInstance()
    ->get(\Magento\Framework\UrlInterface::class);
$wishlistUrl = $urlBuilder->getUrl('wishlist/index/add');
$compareUrl  = $urlBuilder->getUrl('catalog/product_compare/add');
$heartIcon = $block->getViewFileUrl('images/heart.png');
$shuffleIcon = $block->getViewFileUrl('images/shuffle.png');
$eyeIcon = $block->getViewFileUrl('images/eye.png');


$_helper = $block->getData('outputHelper');
$formKey = $block->getFormKey();

if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>

    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    $pos = $block->getPositioned();

    ?>

    <div class="col-lg-12 col-md-8 product_lisiting">
        


              

            <?php if ($viewMode == 'list'){ ?>
                <div class="row list-view" style="display: flex;">
                    <?php foreach ($_productCollection as $_product):

                    $postParams = $block->getAddToCartPostParams($_product); 
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <div class="product-card-category">
                        <div class="product-img"><a href="<?= $_product->getProductUrl() ?>">
                                <?= $productImage->toHtml() ?>
                                </a></div>
                        <div class="mob-design">
                            <div class="product-info-category">
                                <h5><?= $block->stripTags($_product->getName(), null, true); ?></h5>
                                <div class="d-flex align-items-center gap-2 flex-wrap">
                                    <div>
                                        <span class="price">₹<?= number_format($_product->getSpecialPrice(), 2); ?></span>
                                        <span class="old-price">₹<?= number_format($_product->getPrice(), 2); ?></span>
                                    </div>
                                    <span class="stars">★★★★★</span>
                                </div>
                                <p><?= $_product->getShortDescription(); ?></p>
                            </div>
                            <div class="product-buttons list-button">
                                <form data-role="tocart-form"
                                      data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                      data-mage-init='{"catalogAddToCart": {}}'
                                      method="post">
                                    <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                    <?php foreach ($options as $optionItem): ?>
                                        <input type="hidden" name="<?= $escaper->escapeHtml($optionItem['name']) ?>" value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                    <?php endforeach; ?>
                                    <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart btn btn-cart" disabled>
                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                    </button>
                                </form>
<button class="btn btn-buy"
        type="button"
        data-post='<?= $block->escapeHtml(json_encode([
            'action' => $escaper->escapeUrl($postParams['action']),
            'data'   => [
                'product'  => $_product->getId(),
                'qty'      => 1
            ]
        ])) ?>'>
    Buy It Now
</button>                          </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            <?php }elseif($viewMode == 'grid'){ ?>
                  <div class="row card-view" style="display: flex;">
                    <?php foreach ($_productCollection as $_product):

                        $postParams = $block->getAddToCartPostParams($_product); 
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                    <div class="col-lg-3 col-6 p-md-2 p-1">
                        <div class="product-card">
                            <div class="product-image">
                                <a href="<?= $_product->getProductUrl() ?>">
                                <?= $productImage->toHtml() ?>
                                </a>
                                <span class="discount-badge">New</span>
                                <div class="product-actions">
<a href="<?= $_product->getProductUrl() ?>"
       class="action-btn quickview"
       title="<?= $escaper->escapeHtmlAttr(__('Quick View')) ?>"
       data-product-id="<?= (int)$_product->getId(); ?>">
        <img src="<?= $escaper->escapeUrl($eyeIcon) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Quick View')) ?>">
    </a>

    <!-- Wishlist -->
    <a href="#"
       class="action-btn towishlist"
       title="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
       data-post='<?= /* @noEscape */ json_encode([
           'action' => $wishlistUrl,
           'data' => ['product' => (int)$_product->getId()]
       ]) ?>'>
        <img src="<?= $escaper->escapeUrl($heartIcon) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>">
    </a>

    <!-- Compare -->
    <a href="#"
       class="action-btn tocompare"
       title="<?= $escaper->escapeHtmlAttr(__('Compare')) ?>"
       data-post='<?= /* @noEscape */ json_encode([
           'action' => $compareUrl,
           'data' => ['product' => (int)$_product->getId()]
       ]) ?>'>
        <img src="<?= $escaper->escapeUrl($shuffleIcon) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Compare')) ?>">
    </a>                       
    <form data-role="tocart-form"
                                        data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                        action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                        data-mage-init='{"catalogAddToCart": {}}'
                                        method="post">
                                        <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                        <?php foreach ($options as $optionItem): ?>
                                            <input type="hidden" name="<?= $escaper->escapeHtml($optionItem['name']) ?>" value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                        <?php endforeach; ?>
                                        <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                        <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                        <?= $block->getBlockHtml('formkey') ?>

                                        <!-- Normal Add to Cart -->
                                        <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                class="action tocart action-btn btn-cart-cart" data-cart-icon="<?= $block->getViewFileUrl('images/cart.png'); ?>" disabled >
                                            <span><img src="<?= $block->getViewFileUrl("./images/cart.png"); ?>" alt=""></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="product-info">
                                <div class="product-rating">
                                        <?= $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                                </div>
                                <h5 class="product-title"><?= $block->stripTags($_product->getName(), null, true); ?></h5>
                                <div class="product-price">
                                    <span class="current-price">₹<?= number_format($_product->getSpecialPrice(), 2); ?></span>
                                    <span class="original-price">₹<?= number_format($_product->getPrice(), 2); ?></span>
                                </div>
                                <div class="product-buttons">
                                    <form data-role="tocart-form"
                                        data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                        action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                        data-mage-init='{"catalogAddToCart": {}}'
                                        method="post">
                                        <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                        <?php foreach ($options as $optionItem): ?>
                                            <input type="hidden" name="<?= $escaper->escapeHtml($optionItem['name']) ?>" value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                        <?php endforeach; ?>
                                        <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                        <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                        <?= $block->getBlockHtml('formkey') ?>

                                        <!-- Normal Add to Cart -->
                                        <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                class="action tocart btn btn-cart" disabled>
                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>

                                        <!-- Buy Now (uses same AJAX form, but triggers redirect) -->
                                        <button type="button" title="<?= $escaper->escapeHtmlAttr(__('Buy Now')) ?>"
                                                class="action tocart btn btn-buy" disabled>
                                            <span><?= $escaper->escapeHtml(__('Buy Now')) ?></span>
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                            <?php endforeach; ?>

                </div>
                <?php } ?>

    </div>

<?php endif; ?>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
<?php
echo $block->getLayout()
    ->createBlock(\Magento\Review\Block\Product\View\ListView::class)
    ->setTemplate('Magepow_InfiniteScroll::templates/infinitescroll.phtml')
    ->toHtml();
?>
<script type="text/javascript">
require(['jquery'], function ($) {
    'use strict';

    $(document).on('click', '.btn-buy', function () {
        var $form = $(this).closest('form');
        $form.data('buy-now', true); // add a flag
        $form.trigger('submit');     // trigger Magento’s AJAX add to cart
    });
});
</script>


